import { StyleSheet, Dimensions, StatusBar } from "react-native";
import Colors from "../../constants/Colors";
const screenWidth = Math.round(Dimensions.get("window").width);
const SBHeight = StatusBar.currentHeight;
const screenHeight = Math.round(Dimensions.get("window").height) - SBHeight;

const styles = StyleSheet.create({
  promoInput: {
    width: "86.86%",
    alignSelf: "center",
    borderBottomColor: Colors.placeholder,
    borderBottomWidth: 1,
    fontFamily: "poppins-light",
    fontSize: 0.05 * screenWidth,
    textDecorationColor: Colors.input,
    color: Colors.back,
    textAlign: "center",
  },
  pickupTime: {
    fontSize: 0.04 * screenWidth,
    fontFamily: "poppins-light",
    color: Colors.back,
    marginBottom: 0.02 * screenHeight,
  },
  walletCard: {
    backgroundColor: "#fff",
    height: 0.15 * screenHeight,
    width: 0.8527 * screenWidth,
    borderRadius: 0.03333 * screenWidth,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    shadowOpacity: 0.16,
    justifyContent: "space-evenly",
    alignItems: "flex-start",
    marginBottom: 0.03 * screenHeight,
    flexDirection: "row",
  },
  walletHalf: {
    flexGrow: 1,
    flex: 1,
    borderColor: Colors.placeholder,
    width: "50%",
    height: "100%",
    alignItems: "center",
    // paddingTop: 10,
    justifyContent: "space-evenly",
  },
  balance: {
    fontFamily: "poppins-regular",
    fontSize: 0.045 * screenWidth,
    color: Colors.back,
    textAlign: "left",
  },
  toggle: {
    // borderWidth: 1,
    width: 0.138 * screenWidth,
    // marginTop: 15,
    // flexShrink: 1,
  },
  toggleSmall: {
    width: 0.11 * screenWidth,
  },
  balanceAmount: {
    fontFamily: "poppins-regular",
    fontSize: 0.05 * screenWidth,
    color: Colors.back,
    textAlign: "left",
    // marginTop: 10,
  },
  promoCard: {
    backgroundColor: "#fff",
    height: 0.08 * screenHeight,
    width: 0.8527 * screenWidth,
    borderRadius: 0.03333 * screenWidth,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    shadowOpacity: 0.16,
    justifyContent: "space-evenly",
    alignItems: "center",
    // paddingTop: 15,
  },
  addressesPanel: {
    backgroundColor: "#fff",
    height: 0.22 * screenHeight,
    width: 0.8527 * screenWidth,
    borderRadius: 0.03333 * screenWidth,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 4,
    shadowOpacity: 0.16,
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 0.03 * screenHeight,
    overflow: "hidden",
  },
  addressHolder: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexGrow: 1,
    width: "100%",
    paddingStart: 25,
    paddingEnd: 25,
    // borderWidth: 1,
  },
  changeAddressBtn: {
    marginTop: 0,
    marginBottom: 0,
    height: "50%",
    width: "25%",
  },
  changeBtnText: {
    fontSize: 0.028 * screenWidth,
  },
  options: {
    flexDirection: "row",
    height: "65%",
    width: 0.8527 * screenWidth,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  timeSlot: {
    backgroundColor: "#fff",
    flexGrow: 1,
    width: 0.8527 * 0.5 * screenWidth,
    borderBottomWidth: 0.5,
    borderColor: Colors.placeholder,
  },
  optionsText: {
    fontFamily: "poppins-regular",
    fontSize: 0.0444 * screenWidth,
    color: Colors.back,
    textAlign: "center",
    marginTop: 10,
  },
  timeText: {
    fontFamily: "poppins-light",
    fontSize: 0.04 * screenWidth,
    color: Colors.back,
    textAlign: "center",
    marginTop: 10,
  },
  addressName: {
    fontFamily: "poppins-regular",
    fontSize: 0.04 * screenWidth,
    color: Colors.back,
    textAlign: "left",
  },
  address: {
    fontFamily: "poppins-light",
    fontSize: 0.0305 * screenWidth,
    color: Colors.back,
    width: "80%",
    marginTop: -10,
    textAlign: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },

  listContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    paddingTop: 20,
  },
  addressCard: {
    marginTop: 0.0125 * screenHeight,
    marginBottom: 0.0125 * screenHeight,
  },
  header: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    elevation: 10,
    borderRadius: 0.0333 * screenWidth,
  },
  headerText: {
    fontFamily: "poppins-medium",
    fontSize: 0.0225 * screenHeight,
    color: "#fff",
    marginLeft: "6.5%",
  },
  headerIcon: {
    width: 0.197 * screenWidth,
    height: 0.16202 * screenWidth,
    position: "absolute",
    top: 0.01375 * screenHeight,
  },
  buttonListItem: {
    flexGrow: 1,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  buttonText: {
    fontFamily: "poppins-regular",
    fontSize: 0.019 * screenHeight,
    color: "#fff",
  },
  button: {
    width: "66.66%",
    height: 0.0578125 * screenHeight,
    backgroundColor: Colors.primary,
    borderRadius: 0.02890625 * screenHeight,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    marginTop: 25,
    marginBottom: 0.046875 * screenHeight,
  },
  btnContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  confirmationBtn: {
    marginBottom: 0,
    marginTop: 0,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 0.8527 * screenWidth,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 20,
    alignItems: "center",
  },
  wedding: {
    fontFamily: "poppins-light",
    fontSize: 0.03 * screenWidth,
    color: Colors.back,
    textAlign: "left",
  },
});

export default styles;
