import { StyleSheet, Dimensions, StatusBar } from "react-native";
import Colors from "../../constants/Colors";
import { scheduleNotificationAsync } from "expo-notifications";

const screenWidth = Math.round(Dimensions.get("window").width);
const SBHeight = StatusBar.currentHeight;
const screenHeight = Math.round(Dimensions.get("window").height) - SBHeight;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scroll: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  list: {
    marginBottom: 0.034375 * screenHeight,
  },
  address: {
    fontFamily: "poppins-extra-light",
    fontSize: 0.017 * screenHeight,
    color: Colors.back,
    marginBottom: 8,
  },
  addressContainer: {
    // height: 50,
    backgroundColor: "#fff",
    width: 0.71777 * screenWidth,
    // borderWidth: 1,
  },
  addressNameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    // borderWidth: 1,
  },
  addressName: {
    fontFamily: "poppins-regular",
    fontSize: 0.02 * screenHeight,
    color: Colors.back,
  },
  deleteIcon: {
    width: 0.02 * screenWidth,
    height: 0.02 * screenWidth,
  },
  deleteButton: {
    width: 0.05 * screenWidth,
    height: 0.05 * screenWidth,
    justifyContent: "center",
    alignItems: "center",
    // borderWidth: 1,
  },
  noAddresses: {
    fontFamily: "poppins-light",
    fontSize: 0.012 * screenHeight,
    color: Colors.back,
    marginBottom: 0.034375 * screenHeight,
  },
  addressesView: {
    width: "85%",
    borderRadius: 0.01875 * screenHeight,
    backgroundColor: "#fff",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    shadowOpacity: 0.16,
    alignItems: "center",
    // minHeight: 0.104 * screenHeight,
    marginBottom: 0.0375 * screenHeight,
    flexGrow: 1,
    paddingBottom: 10,
  },
  addressesHeader: {
    width: "86.97%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 0.034375 * screenHeight,
    marginBottom: 0.02 * screenHeight,
  },
  addressesHeaderText: {
    fontFamily: "poppins-regular",
    fontSize: 0.025 * screenHeight,
    color: Colors.back,
  },
  plusButton: {
    width: 0.07 * screenWidth,
    aspectRatio: 1,
    borderRadius: 0.035 * screenWidth,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 6,
    shadowOpacity: 0.16,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  plusIcon: {
    width: 0.03 * screenWidth,
    height: 0.03 * screenWidth,
  },
  usernameView: {
    width: "85%",
    height: 0.1875 * screenHeight,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    shadowOpacity: 0.16,
    justifyContent: "center",
    alignItems: "flex-start",
    borderRadius: 0.01875 * screenHeight,
    backgroundColor: "#fff",
    marginBottom: 0.03125 * screenHeight,
  },
  balanceView: {
    width: "85%",
    height: 0.17 * screenHeight,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    shadowOpacity: 0.16,
    justifyContent: "flex-start",
    alignItems: "center",
    borderRadius: 0.01875 * screenHeight,
    backgroundColor: "#fff",
    flexDirection: "row",
  },
  balanceSection: {
    borderColor: Colors.back,
    height: 0.15 * screenHeight,
    width: "40%",
    justifyContent: "center",
    alignItems: "center",
  },
  verticalSeparator: {
    borderColor: Colors.back,
    height: 0.15 * screenHeight,
    width: 0,
    borderRightWidth: 1,
  },
  referralSection: {
    height: 0.15 * screenHeight,
    width: "60%",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 20,
  },
  balanceText: {
    fontFamily: "poppins-light",
    fontSize: 0.022 * screenHeight,
    color: Colors.back,
    textAlignVertical: "center",
  },
  hint: {
    fontFamily: "poppins-extra-light",
    fontSize: 0.015 * screenHeight,
    color: Colors.back,
    textAlignVertical: "center",
    width: "83%",
    marginBottom: 0.02 * screenHeight,
    marginTop: 0.01 * screenHeight,
  },
  shareIcon: {
    width: 20,
    height: 20,
  },
  shareBtn: {
    width: 20,
    height: 20,
  },
  usernameText: {
    fontFamily: "poppins-regular",
    fontSize: 0.025 * screenHeight,
    color: Colors.back,
    textAlignVertical: "center",
    margin: 0.05555 * screenWidth,
    marginTop: 0,
    marginBottom: 0.0125 * screenHeight,
  },
  usernameInput: {
    width: "86.86%",
    alignSelf: "center",
    borderBottomColor: Colors.input,
    borderBottomWidth: 1,
    fontFamily: "poppins-light",
    fontSize: 0.02 * screenHeight,
    textDecorationColor: Colors.input,
    color: Colors.back,
    // marginTop: 0.01 * screenHeight,
    marginBottom: 10,
    padding: 5,
  },
  toggleView: {
    flexDirection: "row",
    width: "85%",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 0.01 * screenHeight,
    marginBottom: 0.03 * screenHeight,
    // borderWidth: 1,
  },
  languageView: {
    flexDirection: "row",
    width: "85%",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: -0.025 * screenHeight,
    marginBottom: 10,
    // borderWidth: 1,
    paddingLeft: 10,
    paddingRight: 10,
  },
  toggleText: {
    fontFamily: "poppins-regular",
    fontSize: 0.021 * screenHeight,
    color: Colors.back,
  },
  toggle: {
    // borderWidth: 1,
    width: 0.138 * screenWidth,

    // flexShrink: 1,
  },
  header: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.profile,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    elevation: 10,
    borderRadius: 0.0333 * screenWidth,
    // borderWidth: 3,
  },
  headerText: {
    fontFamily: "poppins-medium",
    fontSize: 0.023 * screenHeight,
    color: "#fff",
    marginStart: "6.5%",
  },
  headerIcon: {
    width: 0.064861 * screenWidth,
    height: 0.0869166 * screenWidth,
    margin: "6.5%",
  },
  dropdown: {
    width: 10,
    height: 10,
  },
  iosPicker: {
    flexDirection: "row",
    width: 150,
    justifyContent: "space-between",
    padding: 10,
    alignItems: "center",
  },
  lang: {
    fontFamily: "poppins-regular",
    color: Colors.back,
    fontSize: 17,
  },
});

export default styles;
